### ISSUE TITLE
CLI: Output resource usage and measured execution cost

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-contract-cli#25]

**Comment by leighmcculloch** [comment]
@graydon pointed out that with https://github.com/stellar/rs-stellar-contract-env/pull/164 we can use this fn to get the resources used and output them after an invocation:

```rust
host.modify_budget(|budget| ... read fields from budget ...)
```

and

```rust
budget.cpu_insns.get_count()
budget.mem_bytes.get_count()
```

**Comment by graydon** [comment]
You can now use `host.get_budget(|budget| ...)` and there's a new function `budget.get_input(CostType)` that lets you get the _input_ values to the cost-model functions. For example `budget.get_input(CostType::WasmInsnExec)` will return the number of WASM instructions executed, which is not the _input_ to the cost-model function for WASM instructions that bumps the `cpu_insns` count. You probably want to report both, along with a microseconds-of-real-time number, to users.
